.github/workflows/reusable-release-rust.yml
policy-release/action.yaml

Fix release

---

policy-release/action.yaml

See: https://github.com/kubewarden/volumes-psp-policy/runs/4954551693?check_suite_focus=true

Fix conditional in policy-release action

---

.github/workflows/reusable-release-policy-rego.yml

Updates the workflow used to release rego policies removing the "default" field from a required secret used in the workflow.

Remove default value of required secret.

---

kwctl-installer/action.yaml

Updates the kwctl-installer action to install kwctl version v0.3.0.

Update kwctl version installed.

---

setup-kubewarden-cluster-action/README.md
setup-kubewarden-cluster-action/action.yaml

Move the action used to create a K3D cluster and install Kubewarden on it from its own repository to this repository where other actions are stored.
Fix #17

Setup Kubewarden cluster action.

---

policy-build-rust/action.yaml
policy-release/action.yaml
sbom-generator-installer/action.yaml

Updates the worflow files used to build and release the Rust policies to generate the SBOM files.
Fix https://github.com/kubewarden/rust-policy-template/issues/24

SBOM file generation

---

.github/workflows/reusable-release-policy-assemblyscript.yml
.github/workflows/reusable-release-policy-go.yml
.github/workflows/reusable-release-policy-rego.yml
.github/workflows/reusable-release-policy-rust.yml
.github/workflows/reusable-release-policy-swift.yml
policy-release/action.yaml

Remove references to policy hub

---

.github/workflows/reusable-release-policy-rust.yml
.github/workflows/reusable-test-policy-assemblyscript.yml
.github/workflows/reusable-test-policy-go.yml
.github/workflows/reusable-test-policy-rego.yml
.github/workflows/reusable-test-policy-rust.yml
.github/workflows/reusable-test-policy-swift.yml
check-artifacthub/action.yaml
kwctl-installer/action.yaml

Fix https://github.com/kubewarden/github-actions/issues/48
FIx https://github.com/kubewarden/github-actions/issues/47
Tested from my fork, see https://github.com/kubewarden/verify-image-signatures/pull/62.
We could ship this as a new `v2` tag, and since we are going to touch all the policies, we could update the consumption of the github actions. But these changes are backwards compatible, so no need.

feat: Add checking of artifacthub-pkg.yml to v1

---

.github/release-drafter.yml
.github/workflows/release-drafter.yml
.github/workflows/reusable-release-policy-assemblyscript.yml
.github/workflows/reusable-release-policy-go.yml
.github/workflows/reusable-release-policy-rego.yml
.github/workflows/reusable-release-policy-rust.yml
.github/workflows/reusable-release-policy-swift.yml
.github/workflows/reusable-test-policy-assemblyscript.yml
.github/workflows/reusable-test-policy-go.yml
.github/workflows/reusable-test-policy-rego.yml
.github/workflows/reusable-test-policy-rust.yml
.github/workflows/reusable-test-policy-swift.yml
README.md
check-artifacthub/action.yaml
policy-build-go/action.yaml
policy-build-rust/action.yaml
policy-gh-action-dependencies/action.yaml
setup-kubewarden-cluster-action/action.yaml

Create `main` branch from existing `v1` branch.
Make needed changes for a new `v2` tag.
Use the opportunity to refactor and remove unneeded input vars.
Tag `v2.0.0` and `v2` in main once this is merged.
Relates to https://github.com/kubewarden/github-actions/issues/48.
https://github.com/viccuad/verify-image-signatures/actions/runs/4414611656
https://github.com/viccuad/verify-image-signatures/actions/runs/4414611653

Create `v2` version

---

.github/workflows/reusable-release-policy-assemblyscript.yml
.github/workflows/reusable-release-policy-go.yml
.github/workflows/reusable-release-policy-rego.yml
.github/workflows/reusable-release-policy-rust.yml
.github/workflows/reusable-release-policy-swift.yml
.github/workflows/reusable-test-policy-assemblyscript.yml
.github/workflows/reusable-test-policy-go.yml
.github/workflows/reusable-test-policy-rego.yml
.github/workflows/reusable-test-policy-rust.yml
.github/workflows/reusable-test-policy-swift.yml
policy-build-go/action.yaml
policy-gh-action-dependencies/action.yaml

Breaking change.
Not tested yet.

fix!: Use `make annotated-policy.wasm` everywhere

---

.github/workflows/reusable-release-policy-assemblyscript.yml
.github/workflows/reusable-release-policy-go.yml
.github/workflows/reusable-release-policy-rego.yml
.github/workflows/reusable-release-policy-rust.yml
.github/workflows/reusable-release-policy-swift.yml
.github/workflows/reusable-test-policy-assemblyscript.yml
.github/workflows/reusable-test-policy-go.yml
.github/workflows/reusable-test-policy-rego.yml
.github/workflows/reusable-test-policy-rust.yml
.github/workflows/reusable-test-policy-swift.yml
policy-gh-action-dependencies/action.yaml

fix: Reinstalled deleted @
chore: Bump to future v3.0.4
What's that.

fix: Reinstalled deleted @

---

.github/workflows/reusable-release-policy-assemblyscript.yml
.github/workflows/reusable-release-policy-go.yml
.github/workflows/reusable-release-policy-rego.yml
.github/workflows/reusable-release-policy-rust.yml
.github/workflows/reusable-release-policy-swift.yml
.github/workflows/reusable-test-policy-assemblyscript.yml
.github/workflows/reusable-test-policy-go.yml
.github/workflows/reusable-test-policy-rego.yml
.github/workflows/reusable-test-policy-rust.yml
.github/workflows/reusable-test-policy-swift.yml
check-artifacthub/action.yml
policy-gh-action-dependencies/action.yml

Fix https://github.com/kubewarden/github-actions/issues/70.
This ignores the comment header, which may change for community
policies.
Bump to v3.1.1.
Tested locally, edited an artifacthub-pkg.yml header, and run the git diff locally (which diffs the committed one against the working tree one).

fix: Ignore comments on artifacthub-pkg.yml 

---

.github/workflows/reusable-release-policy-assemblyscript.yml
.github/workflows/reusable-release-policy-go.yml
.github/workflows/reusable-release-policy-rego.yml
.github/workflows/reusable-release-policy-rust.yml
.github/workflows/reusable-release-policy-swift.yml
.github/workflows/reusable-test-policy-assemblyscript.yml
.github/workflows/reusable-test-policy-go.yml
.github/workflows/reusable-test-policy-rego.yml
.github/workflows/reusable-test-policy-rust.yml
.github/workflows/reusable-test-policy-swift.yml
kwctl-installer/action.yml
policy-gh-action-dependencies/action.yml

Relates to https://github.com/kubewarden/kubewarden-controller/issues/418.
No real change, yet better to consume 1.6.0 and not an RC.

 deps: Consume kubectl 1.6.0

---

crane-installer/README.md
crane-installer/action.yml
syft-installer/README.md
syft-installer/action.yml

- Add syft installer
- Add crane installer

add new tools

---

.github/workflows/reusable-release-policy-assemblyscript.yml
.github/workflows/reusable-release-policy-go.yml
.github/workflows/reusable-release-policy-rego.yml
.github/workflows/reusable-release-policy-rust.yml
.github/workflows/reusable-release-policy-swift.yml
.github/workflows/reusable-test-policy-assemblyscript.yml
.github/workflows/reusable-test-policy-go.yml
.github/workflows/reusable-test-policy-rego.yml
.github/workflows/reusable-test-policy-rust.yml
.github/workflows/reusable-test-policy-swift.yml
policy-gh-action-dependencies/action.yml

Consume soon to be tagged release
```
sed --in-place 's/3\.1\.4/3\.1\.5/' $(find . -maxdepth 3 -name "*.yml")
```
Once merged I'll tag the 3.1.5 release

chore: prepare for 3.1.5 release

---

.github/workflows/reusable-release-policy-assemblyscript.yml
.github/workflows/reusable-release-policy-go.yml
.github/workflows/reusable-release-policy-rego.yml
.github/workflows/reusable-release-policy-rust.yml
.github/workflows/reusable-release-policy-swift.yml
.github/workflows/reusable-test-policy-assemblyscript.yml
.github/workflows/reusable-test-policy-go.yml
.github/workflows/reusable-test-policy-rego.yml
.github/workflows/reusable-test-policy-rust.yml
.github/workflows/reusable-test-policy-swift.yml
policy-gh-action-dependencies/action.yml

Consume soon to be tagged release
```
sed --in-place 's/3\.1\.5/3\.1\.6/' $(find . -maxdepth 3 -name "*.yml")
```

chore: prepare for 3.1.6 release

---

.github/workflows/reusable-release-policy-assemblyscript.yml
.github/workflows/reusable-release-policy-go.yml
.github/workflows/reusable-release-policy-rego.yml
.github/workflows/reusable-release-policy-rust.yml
.github/workflows/reusable-release-policy-swift.yml
.github/workflows/reusable-test-policy-assemblyscript.yml
.github/workflows/reusable-test-policy-go.yml
.github/workflows/reusable-test-policy-rego.yml
.github/workflows/reusable-test-policy-rust.yml
.github/workflows/reusable-test-policy-swift.yml
policy-gh-action-dependencies/action.yml

Consume soon to be tagged release
```
sed --in-place 's/3\.1\.6/3\.1\.7/' $(find . -maxdepth 3 -name "*.yml")
```

chore: prepare for v3.1.7 release

---

.github/workflows/reusable-release-policy-assemblyscript.yml
.github/workflows/reusable-release-policy-go.yml
.github/workflows/reusable-release-policy-rego.yml
.github/workflows/reusable-release-policy-rust.yml
.github/workflows/reusable-release-policy-swift.yml
.github/workflows/reusable-test-policy-assemblyscript.yml
.github/workflows/reusable-test-policy-go.yml
.github/workflows/reusable-test-policy-rego.yml
.github/workflows/reusable-test-policy-rust.yml
.github/workflows/reusable-test-policy-swift.yml
policy-gh-action-dependencies/action.yml
syft-installer/action.yml

Fix https://github.com/kubewarden/kwctl/issues/550

feat: add inputs.arch to syft-installer

---

.github/workflows/reusable-release-policy-assemblyscript.yml
.github/workflows/reusable-release-policy-go.yml
.github/workflows/reusable-release-policy-rego.yml
.github/workflows/reusable-release-policy-rust.yml
.github/workflows/reusable-release-policy-swift.yml
.github/workflows/reusable-test-policy-assemblyscript.yml
.github/workflows/reusable-test-policy-go.yml
.github/workflows/reusable-test-policy-rego.yml
.github/workflows/reusable-test-policy-rust.yml
.github/workflows/reusable-test-policy-swift.yml
policy-gh-action-dependencies/action.yml
syft-installer/action.yml

Relates to https://github.com/kubewarden/kwctl/issues/550
To test this pull request, you can run the following commands:

fix: Correctly unpack syft for windows

---

kwctl-installer/action.yml

Install latest version of kwctl

chore(deps): update kwctl

---

.github/workflows/reusable-release-policy-assemblyscript.yml
.github/workflows/reusable-release-policy-go.yml
.github/workflows/reusable-release-policy-rego.yml
.github/workflows/reusable-release-policy-rust.yml
.github/workflows/reusable-release-policy-swift.yml
.github/workflows/reusable-test-policy-assemblyscript.yml
.github/workflows/reusable-test-policy-go.yml
.github/workflows/reusable-test-policy-rego.yml
.github/workflows/reusable-test-policy-rust.yml
.github/workflows/reusable-test-policy-swift.yml
policy-gh-action-dependencies/action.yml

Bumping versions to v3.1.10
```shell
sed --in-place 's/3\.1\.9/3\.1\.10/' $(find . -maxdepth 3 -name "*.yml")
```

chore: bump version to v3.1.10

---

policy-build-go/action.yml

chore(deps): update tinygo

---

kwctl-installer/action.yml
setup-kubewarden-cluster-action/action.yml

- Allow to install kwctl latest version
- use kubernetes 1.26 by default

Add option to install latest kwctl

---

kwctl-installer/action.yml

Bumps kwctl to the latest version.

chore: bump kwctl version

---

.github/workflows/reusable-release-policy-assemblyscript.yml
.github/workflows/reusable-release-policy-go.yml
.github/workflows/reusable-release-policy-rego.yml
.github/workflows/reusable-release-policy-rust.yml
.github/workflows/reusable-release-policy-swift.yml
.github/workflows/reusable-test-policy-assemblyscript.yml
.github/workflows/reusable-test-policy-go.yml
.github/workflows/reusable-test-policy-rego.yml
.github/workflows/reusable-test-policy-rust.yml
.github/workflows/reusable-test-policy-swift.yml
policy-gh-action-dependencies/action.yml

chore: bump version to v3.1.12

---

.github/workflows/reusable-release-policy-assemblyscript.yml
.github/workflows/reusable-release-policy-go.yml
.github/workflows/reusable-release-policy-rego.yml
.github/workflows/reusable-release-policy-rust.yml
.github/workflows/reusable-release-policy-swift.yml
.github/workflows/reusable-test-policy-assemblyscript.yml
.github/workflows/reusable-test-policy-go.yml
.github/workflows/reusable-test-policy-rego.yml
.github/workflows/reusable-test-policy-rust.yml
.github/workflows/reusable-test-policy-swift.yml
kwctl-installer/action.yml
policy-gh-action-dependencies/action.yml

- bump kwctl version to v1.10.1
- prepare to release v3.1.15

chore: bump kwctl version to v1.10.1

---

.github/workflows/reusable-release-policy-assemblyscript.yml
.github/workflows/reusable-release-policy-go.yml
.github/workflows/reusable-release-policy-rego.yml
.github/workflows/reusable-release-policy-rust.yml
.github/workflows/reusable-release-policy-swift.yml
.github/workflows/reusable-test-policy-assemblyscript.yml
.github/workflows/reusable-test-policy-go.yml
.github/workflows/reusable-test-policy-rego.yml
.github/workflows/reusable-test-policy-rust.yml
.github/workflows/reusable-test-policy-swift.yml
policy-gh-action-dependencies/action.yml
tarpaulin-install/README.md
tarpaulin-install/action.yml

his action downloads latest stable release of cargo-tarpaulin and installs
that inside of the GitHub action path.
Fix https://github.com/kubewarden/kubewarden-controller/issues/667

feat: github action to install cargo-tarpaulin 

---

.github/workflows/reusable-release-policy-assemblyscript.yml
.github/workflows/reusable-release-policy-go.yml
.github/workflows/reusable-release-policy-rego.yml
.github/workflows/reusable-release-policy-rust.yml
.github/workflows/reusable-release-policy-swift.yml
.github/workflows/reusable-test-policy-assemblyscript.yml
.github/workflows/reusable-test-policy-go.yml
.github/workflows/reusable-test-policy-rego.yml
.github/workflows/reusable-test-policy-rust.yml
.github/workflows/reusable-test-policy-swift.yml
kwctl-installer/action.yml
policy-gh-action-dependencies/action.yml

Bump kwctl-installer to v1.12.0, needed by verify-images-policy

---

setup-kubewarden-cluster-action/action.yml

- remove k3d action that was [denied by security team](https://github.com/rancher/security-team/issues/735#issuecomment-2115299671)
- use default shell
- update cert-manager

Update setup-kubewarden-cluster action

---

.github/workflows/ghrelease.yml

Fix GH release workflow.
Will need to be merged for testing.

ci: Remove unneeded ci job on ghrelease.yml

---

.github/workflows/reusable-release-policy-assemblyscript.yml
.github/workflows/reusable-release-policy-go.yml
.github/workflows/reusable-release-policy-rego.yml
.github/workflows/reusable-release-policy-rust.yml
.github/workflows/reusable-release-policy-swift.yml
.github/workflows/reusable-test-policy-assemblyscript.yml
.github/workflows/reusable-test-policy-go.yml
.github/workflows/reusable-test-policy-rego.yml
.github/workflows/reusable-test-policy-rust.yml
.github/workflows/reusable-test-policy-swift.yml
policy-gh-action-dependencies/action.yml

Updates the version used in the Github action by the version to be released soon.

chore: bump version in use to v3.3.0.

---

.github/workflows/reusable-release-policy-assemblyscript.yml
.github/workflows/reusable-release-policy-go.yml
.github/workflows/reusable-release-policy-rego.yml
.github/workflows/reusable-release-policy-rust.yml
.github/workflows/reusable-release-policy-swift.yml
.github/workflows/reusable-test-policy-assemblyscript.yml
.github/workflows/reusable-test-policy-go.yml
.github/workflows/reusable-test-policy-rego.yml
.github/workflows/reusable-test-policy-rust.yml
.github/workflows/reusable-test-policy-swift.yml
policy-build-go/action.yml
policy-gh-action-dependencies/action.yml

Tested tinygo 0.33.0 manually for  https://github.com/kubewarden/sysctl-psp-policy/pull/51. Unblocks https://github.com/kubewarden/sysctl-psp-policy/pull/51.
Must get tagged as `v3.3.2` after merging.

deps: Move to go 1.23, tinygo 0.33.0 (which supports go 1.23)

---

.github/workflows/reusable-release-policy-assemblyscript.yml
.github/workflows/reusable-release-policy-go.yml
.github/workflows/reusable-release-policy-rego.yml
.github/workflows/reusable-release-policy-rust.yml
.github/workflows/reusable-release-policy-swift.yml
.github/workflows/reusable-test-policy-assemblyscript.yml
.github/workflows/reusable-test-policy-go.yml
.github/workflows/reusable-test-policy-rego.yml
.github/workflows/reusable-test-policy-rust.yml
.github/workflows/reusable-test-policy-swift.yml
kwctl-installer/action.yml
policy-gh-action-dependencies/action.yml

- chore(deps): consume kwctl 1.16.1
- chore(deps): Prepare for v3.3.4 tagging
Once merged I'll handle the tagging

use kwctl 1.16.1

---

.github/workflows/reusable-release-policy-assemblyscript.yml
.github/workflows/reusable-release-policy-go-wasi.yml
.github/workflows/reusable-release-policy-go.yml
.github/workflows/reusable-release-policy-rego.yml
.github/workflows/reusable-release-policy-rust.yml
.github/workflows/reusable-release-policy-swift.yml
.github/workflows/reusable-test-policy-assemblyscript.yml
.github/workflows/reusable-test-policy-go-wasi.yml
.github/workflows/reusable-test-policy-go.yml
.github/workflows/reusable-test-policy-rego.yml
.github/workflows/reusable-test-policy-rust.yml
.github/workflows/reusable-test-policy-swift.yml
policy-gh-action-dependencies/action.yml
push-artifacthub/action.yml

Fix https://github.com/kubewarden/github-actions/issues/141
See this run for the reusable-test-policy-rust workflow:
https://github.com/viccuad/pod-privileged-policy/actions/runs/12416186323

fix: Don't compare version on CI for rust policies

---

renovate-config/default.json
renovate.json

Adds a renovate bot configuration file to be used by the major Kubewarden components.

feat(ci): Common renovate bot configuration

---

renovate-config/default.json

Updates the renovate bot configuration to group minor dependencies bumps together.
Fix https://github.com/kubewarden/kubewarden-controller/issues/976

fix(ci): group minor updates.

---

.github/workflows/release-drafter.yml
.github/workflows/reusable-release-policy-assemblyscript.yml
.github/workflows/reusable-release-policy-go-wasi.yml
.github/workflows/reusable-release-policy-go.yml
.github/workflows/reusable-release-policy-rego.yml
.github/workflows/reusable-release-policy-rust.yml
.github/workflows/reusable-release-policy-swift.yml
.github/workflows/reusable-test-policy-assemblyscript.yml
.github/workflows/reusable-test-policy-go-wasi.yml
.github/workflows/reusable-test-policy-go.yml
.github/workflows/reusable-test-policy-rego.yml
.github/workflows/reusable-test-policy-rust.yml
.github/workflows/reusable-test-policy-swift.yml
check-policy-version/action.yml
policy-build-go-wasi/action.yml
policy-build-rust/action.yml
policy-build-tinygo/action.yml
policy-gh-action-dependencies/action.yml
policy-release/action.yml
push-artifacthub/action.yml

Specify major.minor.patch version when pinning down a GHA.

ci: stricter pinning of GHA

---

kwctl-installer/action.yml

Consume GA version of kwctl instead of RC.

chore: update kwctl version

---

.github/workflows/reusable-release-policy-assemblyscript.yml
.github/workflows/reusable-release-policy-go-wasi.yml
.github/workflows/reusable-release-policy-go.yml
.github/workflows/reusable-release-policy-rego.yml
.github/workflows/reusable-release-policy-rust.yml
.github/workflows/reusable-release-policy-swift.yml
.github/workflows/reusable-test-policy-assemblyscript.yml
.github/workflows/reusable-test-policy-go-wasi.yml
.github/workflows/reusable-test-policy-go.yml
.github/workflows/reusable-test-policy-rego.yml
.github/workflows/reusable-test-policy-rust.yml
policy-gh-action-dependencies/action.yml
push-artifacthub/action.yml

build: Bump version to v4.4.1

---

.github/workflows/reusable-release-policy-assemblyscript.yml
.github/workflows/reusable-release-policy-go-wasi.yml
.github/workflows/reusable-release-policy-go.yml
.github/workflows/reusable-release-policy-rego.yml
.github/workflows/reusable-release-policy-rust.yml
.github/workflows/reusable-release-policy-swift.yml
.github/workflows/reusable-test-policy-assemblyscript.yml
.github/workflows/reusable-test-policy-go-wasi.yml
.github/workflows/reusable-test-policy-go.yml
.github/workflows/reusable-test-policy-rego.yml
.github/workflows/reusable-test-policy-rust.yml
policy-gh-action-dependencies/action.yml
push-artifacthub/action.yml

build: Prepare release v4.4.2

---

policy-gh-action-dependencies/action.yml

Changes described in https://github.com/kubewarden/kubewarden-controller/issues/1096

Install bats npm from official package

---

.github/workflows/reusable-release-policy-assemblyscript.yml
.github/workflows/reusable-release-policy-go-wasi.yml
.github/workflows/reusable-release-policy-go.yml
.github/workflows/reusable-release-policy-rego.yml
.github/workflows/reusable-release-policy-rust.yml
.github/workflows/reusable-release-policy-swift.yml
.github/workflows/reusable-test-policy-go-wasi.yml
.github/workflows/reusable-test-policy-go.yml
.github/workflows/reusable-test-policy-rego.yml
.github/workflows/reusable-test-policy-rust.yml
policy-gh-action-dependencies/action.yml
push-artifacthub/action.yml

Prepare the github actions to v4.4.5 release.

build: prepare release v4.4.5.

---

.github/workflows/reusable-release-policy-assemblyscript.yml
.github/workflows/reusable-release-policy-go-wasi.yml
.github/workflows/reusable-release-policy-go.yml
.github/workflows/reusable-release-policy-rego.yml
.github/workflows/reusable-release-policy-rust.yml
.github/workflows/reusable-release-policy-swift.yml
.github/workflows/reusable-test-policy-go-wasi.yml
.github/workflows/reusable-test-policy-go.yml
.github/workflows/reusable-test-policy-rego.yml
.github/workflows/reusable-test-policy-rust.yml
policy-gh-action-dependencies/action.yml
push-artifacthub/action.yml

Adds the missing "shell" configuration in the github action.

fix: add missing "shell" configuration.

---

.github/workflows/reusable-release-policy-assemblyscript.yml
.github/workflows/reusable-release-policy-catalog.yml
.github/workflows/reusable-release-policy-go-wasi.yml
.github/workflows/reusable-release-policy-go.yml
.github/workflows/reusable-release-policy-rego.yml
.github/workflows/reusable-release-policy-rust.yml
.github/workflows/reusable-release-policy-swift.yml
.github/workflows/reusable-test-policy-go-wasi.yml
.github/workflows/reusable-test-policy-go.yml
.github/workflows/reusable-test-policy-rego.yml
.github/workflows/reusable-test-policy-rust.yml
policy-gh-action-dependencies/action.yml
policy-release/action.yml
push-artifacthub/action.yml

fix: release-policy-catalog, re-include spdx artifacts on policy-release

---

.github/workflows/reusable-release-policy-assemblyscript.yml
.github/workflows/reusable-release-policy-catalog.yml
.github/workflows/reusable-release-policy-go-wasi.yml
.github/workflows/reusable-release-policy-go.yml
.github/workflows/reusable-release-policy-rego.yml
.github/workflows/reusable-release-policy-rust.yml
.github/workflows/reusable-release-policy-swift.yml
.github/workflows/reusable-test-policy-go-wasi.yml
.github/workflows/reusable-test-policy-go.yml
.github/workflows/reusable-test-policy-rego.yml
.github/workflows/reusable-test-policy-rust.yml
policy-gh-action-dependencies/action.yml
push-artifacthub/action.yml

See:
https://github.com/kubewarden/ingress-policy/actions/runs/15112566589
https://github.com/kubewarden/policy-catalog/pull/460

fix: Correctly set payload on reusable-release-policy-catalog, release 4.4.8

---

.github/workflows/reusable-release-policy-assemblyscript.yml
.github/workflows/reusable-release-policy-go-wasi.yml
.github/workflows/reusable-release-policy-go.yml
.github/workflows/reusable-release-policy-rego.yml
.github/workflows/reusable-release-policy-rust.yml
.github/workflows/reusable-release-policy-swift.yml
.github/workflows/reusable-test-policy-go-wasi.yml
.github/workflows/reusable-test-policy-go.yml
.github/workflows/reusable-test-policy-rego.yml
.github/workflows/reusable-test-policy-rust.yml
policy-gh-action-dependencies/action.yml
policy-release/action.yml
push-artifacthub/action.yml

feat: Add a new expect-sbom to policy-release action, and set it , bump to 4.5.0

---

.github/workflows/reusable-release-policy-assemblyscript.yml
.github/workflows/reusable-release-policy-go-wasi.yml
.github/workflows/reusable-release-policy-go.yml
.github/workflows/reusable-release-policy-rego.yml
.github/workflows/reusable-release-policy-rust.yml
.github/workflows/reusable-release-policy-swift.yml
.github/workflows/reusable-test-policy-go-wasi.yml
.github/workflows/reusable-test-policy-go.yml
.github/workflows/reusable-test-policy-rego.yml
.github/workflows/reusable-test-policy-rust.yml
policy-gh-action-dependencies/action.yml
policy-release/action.yml
push-artifacthub/action.yml

fix: Remove duplicated id on policy-release action, bump to 4.5.1

---

policy-build-tinygo/action.yml

deps: Bump tinygo to 0.39.0, for go 1.25 support

---

.github/workflows/reusable-release-policy-assemblyscript.yml
.github/workflows/reusable-release-policy-go-wasi.yml
.github/workflows/reusable-release-policy-go.yml
.github/workflows/reusable-release-policy-rego.yml
.github/workflows/reusable-release-policy-rust.yml
.github/workflows/reusable-release-policy-swift.yml
.github/workflows/reusable-test-policy-go-wasi.yml
.github/workflows/reusable-test-policy-go.yml
.github/workflows/reusable-test-policy-rego.yml
.github/workflows/reusable-test-policy-rust.yml
policy-gh-action-dependencies/action.yml
push-artifacthub/action.yml

Prepare the github-action to the 4.5.6 release.

build: Bump version to 4.5.6

---

.github/workflows/reusable-release-policy-assemblyscript.yml
.github/workflows/reusable-release-policy-go-wasi.yml
.github/workflows/reusable-release-policy-go.yml
.github/workflows/reusable-release-policy-rego.yml
.github/workflows/reusable-release-policy-rust.yml
.github/workflows/reusable-release-policy-swift.yml
.github/workflows/reusable-test-policy-go-wasi.yml
.github/workflows/reusable-test-policy-go.yml
.github/workflows/reusable-test-policy-rego.yml
.github/workflows/reusable-test-policy-rust.yml
policy-gh-action-dependencies/action.yml
push-artifacthub/action.yml

Updates the github action version in use in preparation to a release.

chore: update github actions version.

---

.github/workflows/reusable-release-policy-assemblyscript.yml
.github/workflows/reusable-release-policy-go-wasi.yml
.github/workflows/reusable-release-policy-go.yml
.github/workflows/reusable-release-policy-rego.yml
.github/workflows/reusable-release-policy-rust.yml
.github/workflows/reusable-release-policy-swift.yml
.github/workflows/reusable-test-policy-go-wasi.yml
.github/workflows/reusable-test-policy-go.yml
.github/workflows/reusable-test-policy-rego.yml
.github/workflows/reusable-test-policy-rust.yml
policy-build-rust/action.yml
policy-gh-action-dependencies/action.yml
push-artifacthub/action.yml

Fixes all rust policies failing to build and run e2e tests. [(e.g)](https://github.com/kubewarden/rancher-project-propagate-labels/actions/runs/17998195269/job/51201632686#step:4:204)
To test this pull request, you can run the following commands:

deps: Build rust policies against wasip2 

---

.github/workflows/reusable-release-policy-assemblyscript.yml
.github/workflows/reusable-release-policy-go-wasi.yml
.github/workflows/reusable-release-policy-go.yml
.github/workflows/reusable-release-policy-rego.yml
.github/workflows/reusable-release-policy-rust.yml
.github/workflows/reusable-release-policy-swift.yml
.github/workflows/reusable-test-policy-go-wasi.yml
.github/workflows/reusable-test-policy-go.yml
.github/workflows/reusable-test-policy-rego.yml
.github/workflows/reusable-test-policy-rust.yml
policy-gh-action-dependencies/action.yml
push-artifacthub/action.yml

Updates the github actions changing the version in use in preparation to the next release of the github actions. The command used to update the versions are:
sed --in-place 's/4\.5\.9/4\.5\.10/' $(find . -maxdepth 3 -name "*.yml")

chore: prepare v4.5.10 release.

---

.github/workflows/reusable-release-policy-assemblyscript.yml
.github/workflows/reusable-release-policy-go-wasi.yml
.github/workflows/reusable-release-policy-go.yml
.github/workflows/reusable-release-policy-rego.yml
.github/workflows/reusable-release-policy-rust.yml
.github/workflows/reusable-release-policy-swift.yml
.github/workflows/reusable-test-policy-go-wasi.yml
.github/workflows/reusable-test-policy-go.yml
.github/workflows/reusable-test-policy-rego.yml
.github/workflows/reusable-test-policy-rust.yml
kwctl-installer/action.yml
policy-gh-action-dependencies/action.yml
push-artifacthub/action.yml

Updates the default version used in the kwctl installed action.

fix(kwctl): updates kwctl version
