kubewarden/github-actions

.github/workflows/reusable-release-policy-rust.yml
policy-build-rust/action.yaml
policy-release/action.yaml

Some minor fixes to the release action.
For the Rust action, change the name of the annotated file from `annotated.wasm` to `annotated-policy.wasm`, as discussed inside of one of our policies PR

V1 fix actions

---

policy-release/action.yaml

The workflow PAT is not going to be available for 3rd party policies (the ones created by users).
This is now optional. The notification step takes place only when a PAT is provided by the user.

Release action: do not require workflow PAT

---

.github/workflows/reusable-release-policy-swift.yml
.github/workflows/reusable-test-policy-swift.yml

These are lifted, with minor modifications, from the swift policies.
For successful runs, see:
- `main:`
https://github.com/viccuad/pod-runtime-class-policy/actions/runs/1756243880
https://github.com/viccuad/pod-runtime-class-policy/actions/runs/1756243890
- `tagged`:
https://github.com/viccuad/pod-runtime-class-policy/actions/runs/1756531007: success until opening a PR against policy-hub, for which my token from the fork doesn't have perms. Yet this codepath is the same as the other, already accepted languages.

Add reusable workflows for swift policies

---

.github/workflows/reusable-release-policy-assemblyscript.yml
.github/workflows/reusable-test-policy-assemblyscript.yml

These workflows depend on the Makefile targets on assemblyscript policies, instead of repeating the commands of the Makefile targets in GH Actions.

Add reusable workflows for assemblyscript

---

.github/workflows/reusable-release-policy-rego.yml
.github/workflows/reusable-test-policy-rego.yml
opa-installer/action.yaml

Add reusable workflows for both Rego and OPA policies. One can select the build process between rego or opa with `input.policy-type`.
Add Action to download and install `opa` binary.
Example of workflows:
- test: https://github.com/viccuad/disallow-service-loadbalancer-policy/runs/4979416788?check_suite_focus=true
- release: https://github.com/viccuad/disallow-service-loadbalancer-policy/runs/4979456627?check_suite_focus=true

Add reusable workflows for Rego/OPA policies

---

.github/workflows/reusable-test-policy-go.yml

This is required to make some tests pass because they rely on things like `os.ReadFile` that have been introduced with Go 1.16.

Go test action: use more recent version of Go

---

kwctl-installer/action.yaml

Updates the action used to install kwctl to install the latest version v1.0.1. This way, the latest changes regarding to the signatures verification will be in use avoiding issues when verifying keyless signatures.

Install kwctl v1.0.1

---

policy-build-go/action.yaml

Updates the action used to build the Go policies adding steps to generate the SBOM file using the SPDX format.
Fix https://github.com/kubewarden/go-policy-template/issues/30

SBOM generation for Go policies

---

setup-kubewarden-cluster-action/action.yaml

Cluster is deployed by default with 1 server 0 agent nodes.
This allows to pass k3d arguments, setting default to 1 agent node.

Add 1 agent node to k3d cluster

---

policy-release/action.yaml

We are no longer using policy hub, we can get rid of it during the release steps.

chore: remove references to policy hub

---

setup-kubewarden-cluster-action/action.yaml

Bug description https://github.com/k3s-io/k3s/issues/5835
It should fix EOF errors [e2e tests](https://github.com/kubewarden/kubewarden-controller/actions/workflows/e2e-tests.yml):
```
```

Use newer k3s version to prevent EOF bug

---

policy-build-go/action.yaml
policy-build-rust/action.yaml
policy-gh-action-dependencies/action.yaml

Cosign 2.0 was [released last week](https://blog.sigstore.dev/cosign-2-0-released/) (yay!) but, as expected because semver, it's not backwards compatible (nay!).
Pin cosign-installer GHA so it downloads cosign 1.*.
Latest [cosign-installer downloads cosign 2.*](https://github.com/sigstore/cosign-installer/releases/tag/v3.0.0).
I know this works, because I needed to do this to release my own unrelated viccuad/kwctl:
https://github.com/viccuad/kwctl/actions/runs/4315689467/jobs/7530608694

deps: Pin cosign to 1.*

---

policy-gh-action-dependencies/action.yaml

Reverts kubewarden/github-actions#50
We need to pin `cosign` to 1.*, as there are backwards compat changes.

Revert "chore(deps): update sigstore/cosign-installer action to v3"

---

.github/workflows/reusable-release-policy-assemblyscript.yml
.github/workflows/reusable-release-policy-go.yml
.github/workflows/reusable-release-policy-rego.yml
.github/workflows/reusable-release-policy-rust.yml
.github/workflows/reusable-release-policy-swift.yml
.github/workflows/reusable-test-policy-assemblyscript.yml
.github/workflows/reusable-test-policy-go.yml
.github/workflows/reusable-test-policy-rego.yml
.github/workflows/reusable-test-policy-rust.yml
.github/workflows/reusable-test-policy-swift.yml
check-artifacthub/action.yaml

Relates to https://github.com/kubewarden/kubewarden-controller/issues/389.
Obtain tag string correctly
For reusable-test-policy-* jobs:
check artifacthub-pkg.yml, but ignore the version field, as the tag is not yet created.
For reusable-release-policy-* jobs:
check artifacthub-pkg.yml, and check the version field, as the tag is created.
- On test, example of success, as we can't check the version yet:
https://github.com/viccuad/hostpaths-psp-policy/actions/runs/4436667835
https://github.com/viccuad/hostpaths-psp-policy/actions/runs/4436667844
- On release, example of failure because they forgot to bump the version in all artifacthub-pkg.yml:
https://github.com/viccuad/hostpaths-psp-policy/actions/runs/4436678314/jobs/7785403964
This is fixed by committing the result of:
`touch …

fix: Correctly check artifacthub for policies that use tags

---

.github/workflows/reusable-test-policy-rust.yml
check-artifacthub/action.yaml

Relates to https://github.com/kubewarden/kubewarden-controller/issues/389.
Bumping `version` in artifacthub-pkg.yml not only changes `version`, but `containerImages[].image` and `links[].url`:
```
containersImages:
- name: policy
image: ghcr.io/kubewarden/policies/hostpaths-psp:v0.1.8
links:
- name: policy
url: https://github.com/kubewarden/hostpaths-psp-policy/releases/download/v0.1.8/policy.wasm
```
Naively skip those then. It's not perfect, but it's something.
Locally. What's the worse that can happen. It's already broken.

fix: Ignore artifacthub fields related with `version`

---

kwctl-installer/action.yaml

Install latest version of kwctl: 1.6.0-rc3
This is needed to run e2e tests of context aware policies

chore(deps): use latest version of kwctl

---

check-artifacthub/action.yaml

This will ignore the `install` field line containing the OCI URL of the policy.
Relates to https://github.com/kubewarden/ingress-policy/pull/26.
Tested locally.

fix: Ignore lines with `ghcr.io` if not checking version

---

.github/workflows/reusable-release-policy-assemblyscript.yml
.github/workflows/reusable-release-policy-go.yml
.github/workflows/reusable-release-policy-rego.yml
.github/workflows/reusable-release-policy-rust.yml
.github/workflows/reusable-release-policy-swift.yml
.github/workflows/reusable-test-policy-assemblyscript.yml
.github/workflows/reusable-test-policy-go.yml
.github/workflows/reusable-test-policy-rego.yml
.github/workflows/reusable-test-policy-rust.yml
.github/workflows/reusable-test-policy-swift.yml
policy-build-go/action.yaml
policy-build-rust/action.yaml
policy-gh-action-dependencies/action.yaml

For Go policies:
- Fix build, don't depend on unexistent inputs
For Rust policies:
- Call `make annotated-policy.wasm` so annotations aren't missing usage.

fix: Correctly build Go policies, correctly annotate Rust policies

---

.github/workflows/reusable-release-policy-assemblyscript.yml
.github/workflows/reusable-release-policy-go.yml
.github/workflows/reusable-release-policy-rego.yml
.github/workflows/reusable-release-policy-rust.yml
.github/workflows/reusable-release-policy-swift.yml
.github/workflows/reusable-test-policy-assemblyscript.yml
.github/workflows/reusable-test-policy-go.yml
.github/workflows/reusable-test-policy-rego.yml
.github/workflows/reusable-test-policy-rust.yml
.github/workflows/reusable-test-policy-swift.yml
policy-gh-action-dependencies/action.yaml

Ensure the `use` references are expressed in the proper way.
@viccuad that was a regression introduced with the 3.0.1 release. I wonder if I should now update all the references to be 3.0.2 and tag a v3.0.2 release.
I'm confused... :thinking:

fix: speficy `use` references in the proper way

---

.github/workflows/reusable-release-policy-assemblyscript.yml
.github/workflows/reusable-release-policy-go.yml
.github/workflows/reusable-release-policy-rego.yml
.github/workflows/reusable-release-policy-rust.yml
.github/workflows/reusable-release-policy-swift.yml
.github/workflows/reusable-test-policy-assemblyscript.yml
.github/workflows/reusable-test-policy-go.yml
.github/workflows/reusable-test-policy-rego.yml
.github/workflows/reusable-test-policy-rust.yml
.github/workflows/reusable-test-policy-swift.yml
policy-gh-action-dependencies/action.yml

Hoping that it fixes https://github.com/kubewarden/verify-image-signatures/actions/runs/4859474900/jobs/8662858899#step:7:10.
Tested bats 1.8.2 locally against the verify-image-signatures e2e tests.
Needs to be tagged as v3.1.4.

deps: Bump bats to 1.8.2

---

policy-build-go/action.yml
policy-build-rust/action.yml
policy-gh-action-dependencies/action.yml
policy-release/action.yml

Updates the CI scripts updating the cosign-installer to v3. Thus, the cosign version now is v2. Which has breaking changes requiring some changes on how the command is called and removing the need of using environment variable to enable keyless signature.
Related to https://github.com/kubewarden/kubewarden-controller/issues/411

Updates cosign to v2.

---

policy-build-go/action.yml

bumps tinygo to the latest stable version. 
-
-

build: bump tinygo version to 0.28.1

---

setup-kubewarden-cluster-action/action.yml

I think we should use latest available chart for image tests.
We also use `--devel` parameter in e2e tests Makefile.

Use rc helm charts for tests

---

.github/workflows/reusable-release-policy-assemblyscript.yml
.github/workflows/reusable-release-policy-go.yml
.github/workflows/reusable-release-policy-rego.yml
.github/workflows/reusable-release-policy-rust.yml
.github/workflows/reusable-release-policy-swift.yml
.github/workflows/reusable-test-policy-assemblyscript.yml
.github/workflows/reusable-test-policy-go.yml
.github/workflows/reusable-test-policy-rego.yml
.github/workflows/reusable-test-policy-rust.yml
.github/workflows/reusable-test-policy-swift.yml
kwctl-installer/action.yml
policy-gh-action-dependencies/action.yml

Consume kwctl v1.9.0-rc2 on the kwctl-installer.
This unblocks the release of the new raw policies.
This will be tagged v3.1.11 in main.

deps: bump kwctl-installer to v1.9.0-rc2

---

.github/workflows/reusable-release-policy-assemblyscript.yml
.github/workflows/reusable-release-policy-go.yml
.github/workflows/reusable-release-policy-rego.yml
.github/workflows/reusable-release-policy-rust.yml
.github/workflows/reusable-release-policy-swift.yml
.github/workflows/reusable-test-policy-assemblyscript.yml
.github/workflows/reusable-test-policy-go.yml
.github/workflows/reusable-test-policy-rego.yml
.github/workflows/reusable-test-policy-rust.yml
.github/workflows/reusable-test-policy-swift.yml
policy-build-go/action.yml
policy-gh-action-dependencies/action.yml

Latest version of Go introduces the concept of [toolchain](https://go.dev/blog/toolchain).
This brings a new keyword inside of `go.mod`. This keyword can be understood using Go 1.21 or later.
Even though our Go policies are built with TinyGo, TinyGo requires the official Go compiler to perform some tasks.
Because of that, we have to ensure the latest stable release of the Go compiler is installed inside of the build environment. We cannot rely on what is shipped out of the box with the GH runner image.
This PR contains two commits:
- fix: ensure TinyGo policies build without errors
- Prepare for 3.1.16 tagging
Once merged, I'll create the `v3.1.16` tag.

fix tinygo build caused by go toolchain

---

.github/workflows/reusable-release-policy-assemblyscript.yml
.github/workflows/reusable-release-policy-go.yml
.github/workflows/reusable-release-policy-rego.yml
.github/workflows/reusable-release-policy-rust.yml
.github/workflows/reusable-release-policy-swift.yml
.github/workflows/reusable-test-policy-assemblyscript.yml
.github/workflows/reusable-test-policy-go.yml
.github/workflows/reusable-test-policy-rego.yml
.github/workflows/reusable-test-policy-rust.yml
.github/workflows/reusable-test-policy-swift.yml
policy-build-go/action.yml
policy-gh-action-dependencies/action.yml

Be explicit about go version
The `setup-go` action cannot install the `stable` version of Go because tinygo supports only a specific range of Go versions.
Currently, the latest stable release of Go is 1.22. However, latest stable version of Tinygo supports only Go >= 1.18 and <=1.21.
Once merged, I'll tag 3.1.17

specify go version to be installed

---

setup-kubewarden-cluster-action/action.yml

E2e tests fail with missing shell error:
https://github.com/kubewarden/kubewarden-controller/actions/runs/9151560113/job/25157803627
There is github issue already about default shell not working on composite actions:
https://github.com/orgs/community/discussions/46670

Default shell is broken on composite actions

---

.github/workflows/reusable-release-policy-assemblyscript.yml
.github/workflows/reusable-release-policy-go.yml
.github/workflows/reusable-release-policy-rego.yml
.github/workflows/reusable-release-policy-rust.yml
.github/workflows/reusable-release-policy-swift.yml
.github/workflows/reusable-test-policy-assemblyscript.yml
.github/workflows/reusable-test-policy-go.yml
.github/workflows/reusable-test-policy-rego.yml
.github/workflows/reusable-test-policy-rust.yml
.github/workflows/reusable-test-policy-swift.yml
policy-build-rust/action.yml
policy-gh-action-dependencies/action.yml

The `wasm32-wasi` target is deprecated and is has already been renamed `wasm32-wasip1`
See https://blog.rust-lang.org/2024/04/09/updates-to-rusts-wasi-targets.html
Also, prepare for 3.1.20 release of this action

rust policies move to wasm32 wasip1

---

.github/workflows/reusable-release-policy-assemblyscript.yml
.github/workflows/reusable-release-policy-go.yml
.github/workflows/reusable-release-policy-rego.yml
.github/workflows/reusable-release-policy-rust.yml
.github/workflows/reusable-release-policy-swift.yml
.github/workflows/reusable-test-policy-assemblyscript.yml
.github/workflows/reusable-test-policy-go.yml
.github/workflows/reusable-test-policy-rego.yml
.github/workflows/reusable-test-policy-rust.yml
.github/workflows/reusable-test-policy-swift.yml
policy-build-go/action.yml
policy-gh-action-dependencies/action.yml

Use latest version of tinygo.
**Warning:** this will require the policies to update to latest version of our KW Go SDK
Finally, I've prepared the code for the upcoming 3.1.21 tag. I'm going to create it as soon as we merge this PR.

update tinygo version

---

.github/workflows/ghrelease.yml

Add ghrelease workflow to create GH releases
This workflow is not reusable. It marks the existing draft release from release-drafter as latest release.
This would need to be in main and get a new tag to be tested.

ci: Add ghrelease workflow to create GH releases

---

setup-kubewarden-cluster-action/action.yml

Some E2E CI jobs are failing due the slowness of the installation process. This commit doubles the timeout to 10m.
Example of failing job: https://github.com/kubewarden/kubewarden-controller/actions/runs/10068249606/job/27833330861

fix: increase Helm timeout

---

.github/workflows/reusable-release-policy-assemblyscript.yml
.github/workflows/reusable-release-policy-go.yml
.github/workflows/reusable-release-policy-rego.yml
.github/workflows/reusable-release-policy-rust.yml
.github/workflows/reusable-release-policy-swift.yml
.github/workflows/reusable-test-policy-assemblyscript.yml
.github/workflows/reusable-test-policy-go.yml
.github/workflows/reusable-test-policy-rego.yml
.github/workflows/reusable-test-policy-rust.yml
.github/workflows/reusable-test-policy-swift.yml
policy-build-rust/action.yml
policy-gh-action-dependencies/action.yml

Relates to https://github.com/kubewarden/kubewarden-controller/issues/855#issuecomment-2310453623.
See CI for https://github.com/viccuad/verify-image-signatures/pull/1.
Example: https://github.com/viccuad/verify-image-signatures/actions/runs/10575780671/job/29300167919#step:5:56
(e2e tests run which is the important part, expected failure).
To be tagged as 3.3.3.
The build of the policy prior to e2e tests takes 40s on a complex policy (such as verify-image-signatures). This happens in parallel with other CI jobs (unit tests, lints..).

feat: Run e2e tests on CI job for Rust policies 

---

.github/workflows/reusable-release-policy-assemblyscript.yml
.github/workflows/reusable-release-policy-go-wasi.yml
.github/workflows/reusable-release-policy-go.yml
.github/workflows/reusable-release-policy-rego.yml
.github/workflows/reusable-release-policy-rust.yml
.github/workflows/reusable-release-policy-swift.yml
.github/workflows/reusable-test-policy-assemblyscript.yml
.github/workflows/reusable-test-policy-go-wasi.yml
.github/workflows/reusable-test-policy-go.yml
.github/workflows/reusable-test-policy-rego.yml
.github/workflows/reusable-test-policy-rust.yml
.github/workflows/reusable-test-policy-swift.yml
policy-build-go-wasi/action.yml
policy-build-tinygo/action.yml
policy-gh-action-dependencies/action.yml

We just realized some Go-WASI policies are not signed with sigstore. That happens because we never uniformed our Go-WASI policies to use the same set of actions used by the TinyGo ones.
Now that we have go-wasi policies, we must be able to differentiate between policies built using waPC + TinyGo and the ones that are built using the official Go compiler and the WASI policy mode offered by Kubewarden.
The current tinygo policies will keep working as expected, without any change from us.
The Go-WASI policies will have to be changed to use the new reusable workflows defined by this PR.

add go wasi policies

---

.github/workflows/reusable-release-policy-assemblyscript.yml
.github/workflows/reusable-release-policy-go-wasi.yml
.github/workflows/reusable-release-policy-go.yml
.github/workflows/reusable-release-policy-rego.yml
.github/workflows/reusable-release-policy-rust.yml
.github/workflows/reusable-release-policy-swift.yml
.github/workflows/reusable-test-policy-assemblyscript.yml
.github/workflows/reusable-test-policy-go-wasi.yml
.github/workflows/reusable-test-policy-go.yml
.github/workflows/reusable-test-policy-rego.yml
.github/workflows/reusable-test-policy-rust.yml
.github/workflows/reusable-test-policy-swift.yml
check-artifacthub/action.yml
opa-installer/action.yml
policy-gh-action-dependencies/action.yml
policy-release/action.yml
push-artifacthub/action.yml

Fix https://github.com/kubewarden/kubewarden-controller/issues/806
Recommend review by commit.
See also working monorepo repo at https://github.com/viccuad/rego-policies.
For monorepo policies:
- Successfully failing release with tag `ControllerContainerBlockSSHPort/v0.0.3`
because artifacthub-pkg.yml hasn't been updated:
https://github.com/viccuad/rego-policies/actions/runs/12352787565/job/34470569919
- Successful run and release with tag `ControllerContainerBlockSSHPort/v0.0.4`:
https://github.com/viccuad/rego-policies/actions/runs/12352849151
For Normal policies:
- Successful CI run:
https://github.com/viccuad/disallow-service-loadbalancer-policy/actions/runs/12352648538
- Successful :latest release:
https://github.com/viccuad/disallow-service-loadbalancer-policy/actions/runs/1235264855 …

feat: Support policies in folders for reusable workflows

---

policy-build-tinygo/action.yml

Use latest stable release of tinygo: 0.34.0
@viccuad: maybe we could merge that before you tag the next version of this repo

chore(deps): update version of tinygo

---

.github/workflows/reusable-release-policy-assemblyscript.yml
.github/workflows/reusable-release-policy-go-wasi.yml
.github/workflows/reusable-release-policy-go.yml
.github/workflows/reusable-release-policy-rego.yml
.github/workflows/reusable-release-policy-rust.yml
.github/workflows/reusable-release-policy-swift.yml
.github/workflows/reusable-test-policy-assemblyscript.yml
.github/workflows/reusable-test-policy-go-wasi.yml
.github/workflows/reusable-test-policy-go.yml
.github/workflows/reusable-test-policy-rego.yml
.github/workflows/reusable-test-policy-rust.yml
.github/workflows/reusable-test-policy-swift.yml
policy-gh-action-dependencies/action.yml

This fixes `:latest` and CI for repos where the policy has never had a tag. E.g of failure without this fix:
https://github.com/kubewarden/raw-mutation-wasi-policy/actions/runs/12430796708/job/34706956927
tested locally.
Once merged, needs to be tagged as `v3.4.2`.

fix: Support repos where there's no tag at all 

---

.github/workflows/reusable-release-policy-assemblyscript.yml
.github/workflows/reusable-release-policy-go-wasi.yml
.github/workflows/reusable-release-policy-go.yml
.github/workflows/reusable-release-policy-rego.yml
.github/workflows/reusable-release-policy-rust.yml
.github/workflows/reusable-release-policy-swift.yml
.github/workflows/reusable-test-policy-assemblyscript.yml
.github/workflows/reusable-test-policy-go-wasi.yml
.github/workflows/reusable-test-policy-go.yml
.github/workflows/reusable-test-policy-rego.yml
.github/workflows/reusable-test-policy-rust.yml
.github/workflows/reusable-test-policy-swift.yml
policy-gh-action-dependencies/action.yml
push-artifacthub/action.yml

fix: Push fast-forward on artifacthub branch
When updating the artifacthub branch for releasing on artifacthub, do a
fast-forward with performing a `git pull` beforehand (with `git pull
--rebase` instead of plain `git pull` to not have merge commits).
If not, git will not accept the push as the remote contains work
that we do not. This is usually the case as we check out the repo
with actions/checkout@v4 and we don't check out every branch, hence
when we do a `git checkout artifacthub` we actually create a new
branch.
Example of failure to fix:
https://github.com/kubewarden/deprecated-api-versions-policy/actions/runs/12646725806/job/35237961380
Not tested.
To be tagged as `v3.4.3`.
One could also change how `actions/checkout@v4` performs the checkout to have a local artifacthub branch, …

fix: Correctly push to artifacthub branch, fix artifacthub policy release

---

policy-build-tinygo/action.yml

Starting from tinygo 0.35.0, our policies cannot run because of an issue inside of wapc's wasmtime-provider crate.
The issue has been fixed upstream and it will be part of the next release of Kubewarden (1.21.0).
In the meantime, we have to downgrade the version of tinygo used by our GHA, otherwise e2e tests will fail and it will be impossible to release fixes for the tinygo policies.

fix: temporarily downgrade tinygo version

---

.github/workflows/reusable-release-policy-assemblyscript.yml
.github/workflows/reusable-release-policy-go-wasi.yml
.github/workflows/reusable-release-policy-go.yml
.github/workflows/reusable-release-policy-rego.yml
.github/workflows/reusable-release-policy-rust.yml
.github/workflows/reusable-release-policy-swift.yml
.github/workflows/reusable-test-policy-assemblyscript.yml
.github/workflows/reusable-test-policy-go-wasi.yml
.github/workflows/reusable-test-policy-go.yml
.github/workflows/reusable-test-policy-rego.yml
.github/workflows/reusable-test-policy-rust.yml
.github/workflows/reusable-test-policy-swift.yml
policy-gh-action-dependencies/action.yml
policy-release/action.yml
push-artifacthub/action.yml

Fix https://github.com/kubewarden/github-actions/issues/147
When artifacthub branch doesn't exist yet:
https://github.com/viccuad/deprecated-api-versions-policy/actions/runs/12809241745
corresponds to commit https://github.com/viccuad/deprecated-api-versions-policy/commit/3a0444b3b0cb7f216a4f6c1236a8f1b907f38f59
(note: when making this v0.1.0-dev  tag, the history for v0.1.0-dev already existed in main but was correctly not taken into consideration).
When artifacthub branch exists (hence appending commits to history):
https://github.com/viccuad/deprecated-api-versions-policy/actions/runs/12809322801
corresponds to commit https://github.com/viccuad/deprecated-api-versions-policy/commit/d0651140e02800e00a1314cf6780ca8389480829
(note: v0.1.0-dev was already released, this releases …

fix: Correctly pull from artifacthub and push needed files

---

.github/workflows/reusable-release-policy-assemblyscript.yml
.github/workflows/reusable-release-policy-go-wasi.yml
.github/workflows/reusable-release-policy-go.yml
.github/workflows/reusable-release-policy-rego.yml
.github/workflows/reusable-release-policy-rust.yml
.github/workflows/reusable-release-policy-swift.yml
.github/workflows/reusable-test-policy-assemblyscript.yml
.github/workflows/reusable-test-policy-go-wasi.yml
.github/workflows/reusable-test-policy-go.yml
.github/workflows/reusable-test-policy-rego.yml
.github/workflows/reusable-test-policy-rust.yml
.github/workflows/reusable-test-policy-swift.yml
kwctl-installer/action.yml
policy-build-tinygo/action.yml
policy-gh-action-dependencies/action.yml

- Update tinygo to latest version
- Update kwctl to latest version. This is required to have policies   built with latest version of tinygo to work. Moreover, this is   required to address the breaking change introduced on Sigstore's TUF   repository
Once this is merged I'll tag the 3.4.6 release

update tinygo and kwctl

---

.github/workflows/reusable-release-policy-assemblyscript.yml
.github/workflows/reusable-release-policy-go-wasi.yml
.github/workflows/reusable-release-policy-go.yml
.github/workflows/reusable-release-policy-rego.yml
.github/workflows/reusable-release-policy-rust.yml
.github/workflows/reusable-release-policy-swift.yml
.github/workflows/reusable-test-policy-assemblyscript.yml
.github/workflows/reusable-test-policy-go-wasi.yml
.github/workflows/reusable-test-policy-go.yml
.github/workflows/reusable-test-policy-rego.yml
.github/workflows/reusable-test-policy-rust.yml
.github/workflows/reusable-test-policy-swift.yml
kwctl-installer/action.yml
policy-build-tinygo/action.yml
policy-gh-action-dependencies/action.yml

This will allow to build policies that have beeb bumped to go 1.24.
Locally with https://github.com/kubewarden/safe-labels-policy/pull/69.

deps: Bump kwctl, tinygo to 0.36.0 with go 1.24 support 

---

renovate-config/policies.json

Create a shared configuration of renovatebot to be used by policies repositories.
This policy is based on a mix between the one we created for [our reference policy](https://github.com/kubewarden/pod-privileged-policy/blob/main/renovate.json) and the one we use for kwctl/policy-server/controller/audit-scanner.

ci: add renovate config for policies

---

renovate.json

On the next run, renovatebot will update all our GHA actions to be pinned with checksum.

ci: pin GHA by checksum

---

.github/workflows/reusable-release-policy-assemblyscript.yml
.github/workflows/reusable-release-policy-go-wasi.yml
.github/workflows/reusable-release-policy-go.yml
.github/workflows/reusable-release-policy-rego.yml
.github/workflows/reusable-release-policy-rust.yml
.github/workflows/reusable-release-policy-swift.yml
.github/workflows/reusable-test-policy-go-wasi.yml
.github/workflows/reusable-test-policy-go.yml
.github/workflows/reusable-test-policy-rego.yml
.github/workflows/reusable-test-policy-rust.yml
policy-gh-action-dependencies/action.yml
policy-release-catalog/action.yml
push-artifacthub/action.yml

This PR introduces the necessary repository dispatch for the [policy-catalog](https://github.com/kubewarden/policy-catalog) to update the catalog when a new policy version is released. It includes a new composite action, `policy-release-catalog`, which builds the JSON payload conditionally. If the repository is a monorepo, `policy-name` and `policy-working-dir` are passed accordingly.  
Triggering the workflow requires the `release-catalog` input set to true and the `WORKFLOW_PAT` personal access token passed as a secret., meaning all policies must be updated. 
It also fixes a bug in the `push-artifacthub` composite action, where the directory was not being created during the initial setup of ArtifactHub in a monorepo.
Tested in forked repositories:  
- …

feat: add policy catalog repository dispatch

---

.github/workflows/reusable-release-policy-catalog.yml

The release catalog workflow should only be triggered if the ref is a tag. This worked in some repositories, like the monorepo, where tags events triggered the  parent workflow. However, in other repositories, we want to trigger the release of the main branch (latest tag), so this is needed to skip the workflow in that scenario.

fix: skip release catalog if ref is not a tag

---

.github/workflows/reusable-release-policy-assemblyscript.yml
.github/workflows/reusable-release-policy-catalog.yml
.github/workflows/reusable-release-policy-go-wasi.yml
.github/workflows/reusable-release-policy-go.yml
.github/workflows/reusable-release-policy-rego.yml
.github/workflows/reusable-release-policy-rust.yml
.github/workflows/reusable-release-policy-swift.yml
.github/workflows/reusable-test-policy-go-wasi.yml
.github/workflows/reusable-test-policy-go.yml
.github/workflows/reusable-test-policy-rego.yml
.github/workflows/reusable-test-policy-rust.yml
policy-gh-action-dependencies/action.yml
push-artifacthub/action.yml

This PR replaces the `WORKFLOW_PAT` secret with the [create-github-app-token action](https://github.com/actions/create-github-app-token?tab=readme-ov-file#create-a-token-for-all-repositories-in-another-owners-installation).  
Related to https://github.com/kubewarden/kubewarden-controller/issues/1070
It now requires `APP_ID` and `APP_PRIVATE_KEY` as secrets.  
This is a breaking change since it modifies the required input secrets.

feat!(release-policy-catalog): generate token programmatically

---

.github/workflows/reusable-release-policy-assemblyscript.yml
.github/workflows/reusable-release-policy-go-wasi.yml
.github/workflows/reusable-release-policy-go.yml
.github/workflows/reusable-release-policy-rego.yml
.github/workflows/reusable-release-policy-rust.yml
.github/workflows/reusable-release-policy-swift.yml
.github/workflows/reusable-test-policy-assemblyscript.yml
.github/workflows/reusable-test-policy-go-wasi.yml
.github/workflows/reusable-test-policy-go.yml
.github/workflows/reusable-test-policy-rego.yml
.github/workflows/reusable-test-policy-rust.yml
policy-gh-action-dependencies/action.yml
push-artifacthub/action.yml

Fix https://github.com/kubewarden/kubewarden-controller/issues/1050
Tagging this v4.4.0 will release:
- the addition of the new reusable-release-pr, reusable-release-tag workflows
- commits direct to main [here](https://github.com/kubewarden/github-actions/commits/main/?since=2025-04-04&until=2025-04-04)  (it was easier than opening PRs for small things..)
The newly added reusable-release-pr, reusable-release-tag worfklows where consumed in several policies,
and tested by triggering the "open-release-pr" job manually, merging the resulting PR, and seeing that a new tag and release was created.
See:
- https://github.com/kubewarden/verify-image-signatures/pull/162 resulting in https://github.com/kubewarden/verify-image-signatures/releases/tag/v0.3.2
- …

build: Bump version to v4.4.0

---

.github/workflows/reusable-release-policy-catalog.yml

Replaces `artifacthub_pkg_path` with `policy_working_dir`
related to https://github.com/kubewarden/policy-catalog/pull/379 and https://github.com/kubewarden/policy-catalog/issues/345

ci(release-policy-catalog): replace artifacthub_pkg_path with policy_working_dir

---

.github/workflows/reusable-release-policy-assemblyscript.yml
.github/workflows/reusable-release-policy-go-wasi.yml
.github/workflows/reusable-release-policy-go.yml
.github/workflows/reusable-release-policy-rego.yml
.github/workflows/reusable-release-policy-rust.yml
.github/workflows/reusable-release-policy-swift.yml
.github/workflows/reusable-test-policy-assemblyscript.yml
.github/workflows/reusable-test-policy-go-wasi.yml
.github/workflows/reusable-test-policy-go.yml
.github/workflows/reusable-test-policy-rego.yml
.github/workflows/reusable-test-policy-rust.yml
policy-gh-action-dependencies/action.yml
policy-release/action.yml
push-artifacthub/action.yml

This fixes errors such as https://github.com/kubewarden/rego-policies-library/actions/runs/14490693920/job/40646274374
When performing https://github.com/kubewarden/github-actions/commit/64bfecfcf13b3f3057cf5aa9e20fcf172573f753, we didn't take into account the working-policy-dir.
Untested. Shamelessly.

fix: Correctly use policy-working-dir on policy-release, release v4.4.3

---

.github/workflows/reusable-release-policy-assemblyscript.yml
.github/workflows/reusable-release-policy-go-wasi.yml
.github/workflows/reusable-release-policy-go.yml
.github/workflows/reusable-release-policy-rego.yml
.github/workflows/reusable-release-policy-rust.yml
.github/workflows/reusable-release-policy-swift.yml
.github/workflows/reusable-test-policy-assemblyscript.yml
.github/workflows/reusable-test-policy-go-wasi.yml
.github/workflows/reusable-test-policy-go.yml
.github/workflows/reusable-test-policy-rego.yml
.github/workflows/reusable-test-policy-rust.yml
policy-gh-action-dependencies/action.yml
policy-release/action.yml
push-artifacthub/action.yml

Fixes errors such as https://github.com/kubewarden/rego-policies-library/actions/runs/14491317023/job/40649089321#step:11:112
uh?

fix: Don't use GH draft releases on monorepos

---

.github/workflows/reusable-release-policy-catalog.yml

Part of https://github.com/kubewarden/kubewarden-controller/issues/1099.
Tested locally with:
```console
$ cat payload.json
{
"event_type": "release-policy",
"client_payload": {
"owner": "viccuad",
"repo": "deprecated-api-versions-policy",
"tag": "v1.0.0"
}
}
$ gh api repos/viccuad/policy-catalog/dispatches -X POST  --input payload.json
```

ci: Substitute peter-evans/repository-dispatch with gh cli

---

policy-release/action.yml

In a previous commit (93fc9b2ceeb5d87d13ee52254b48fc8b11c4e64a) the "]" closing the array has been removed accidentally. This commit fix this syntax error.

fix: syntax error in policy-release action.

---

.github/workflows/reusable-test-policy-rust.yml
policy-build-rust/action.yml

Removes the usage of the deprecated actions-rs Github actions. Replacing it by running the rustup and cargo command directly relying on the binaries installed in the workflow runner.
Related to https://github.com/kubewarden/kubewarden-controller/issues/1092 and https://github.com/kubewarden/kubewarden-controller/issues/1093

chore: remove actions-rs github actions.

---

kwctl-installer/action.yml

To allow the release of the new high risk service account blocker policy, we need to update the kwctl installed to v1.27.0-alpha2. It has the kubernetes/can-i host capability with the correct input and output json

fix(kwctl-installer): install v1.27.0-alpha2

---

.github/workflows/reusable-test-policy-rust.yml

Change the reusable rust test action to support projects that make use of workspaces.

feat: support rust projects that make use of workspaces

---

kwctl-installer/action.yml

Updates the kwctl installer updating the default kwctl version installed to v1.28.1.
This is required to make CI on this [PR](https://github.com/kubewarden/policy-sdk-js/pull/189) happy

fix(kwctl): updates kwctl version in use.
